In [ ]:
import numpy as np

# Crop Choice Model Tests

This notebook will test the integrated function of the model. 

In [1]:
import sys
sys.path.append('/Users/johnkucharski/Documents/source/cropchoice')
import water
import crops
import system

The block of code below builds a "central planner" contained in the **System.CentralPlanner**. This is constructed from:

1. **G**: Groundwater - a groundwater object described in the *water.ipynb* notebook.
2. **S**: Surfacewater -  a surfacewater object described in the *water.ipynb* notebook.
3. **crops**: np.ndarray[shape=(x,1), dtype=Crop] - a numpy array of *crop* objects described in the *crops.ipynb* notebook.
4. **portfolio**: np.ndarray[shape=(x,1), dtype=unsigned integer] - an initial allocation of crops.

**NOTE**: the position of crop items in the *crops* array must match the position of the area allocated to them in the **portfolio** array.  

In [2]:
cp = system.CentralPlanner()
print(cp)

CentralPlanner(G=Groundwater(active=True, deficit=0.0, max_deficit=inf, sustainable_yield=0.0, pump_cost_function=<function exponential.<locals>.f at 0x11a0e4160>), S=Surfacewater(available=0, unit_cost=1), crops=array([Fallow(name='FALLOW'),
       Annual(name='ANNUAL', unit_costs=UnitCost(startup_cost=0, non_water_cost=1), production_fx=<function unit_production.<locals>.f at 0x11a0e5870>),
       Perennial(name='PERENNIAL', unit_costs=UnitCost(startup_cost=0, non_water_cost=1), production_fx=<function unit_production.<locals>.f at 0x11a0e52d0>)],
      dtype=object), portfolio=array([50, 25, 25], dtype=uint32))


#### system.Planner.plan(inputs: np.ndarray)

The **plan()**

In [3]:
# ETo, Kc, P, Price, r
inputs = np.array([[1, 0, 1, 0, 0.1],
                   [1, 1, 1, 2, 0.1],
                   [1, 2, 1, 2.1, 0.1]])
out = cp.plan(inputs)
# id, d, sw, gw, price, mr, mc, npv
print(out[0:5,:])


[[ 2.  2.  0.  1.  1. 21. 20.  1.]
 [ 2.  2.  0.  1.  1. 21. 20.  1.]
 [ 2.  2.  0.  1.  1. 21. 20.  1.]
 [ 2.  2.  0.  1.  1. 21. 20.  1.]
 [ 2.  2.  0.  1.  1. 21. 20.  1.]]


In [4]:
cp = system.CentralPlanner(G=water.Groundwater(active=False), S=water.Surfacewater(available=2))
print(cp)


CentralPlanner(G=Groundwater(active=False, deficit=0.0, max_deficit=inf, sustainable_yield=0.0, pump_cost_function=<function exponential.<locals>.f at 0x11a0e4160>), S=Surfacewater(available=2, unit_cost=1), crops=array([Fallow(name='FALLOW'),
       Annual(name='ANNUAL', unit_costs=UnitCost(startup_cost=0, non_water_cost=1), production_fx=<function unit_production.<locals>.f at 0x11a0e5870>),
       Perennial(name='PERENNIAL', unit_costs=UnitCost(startup_cost=0, non_water_cost=1), production_fx=<function unit_production.<locals>.f at 0x11a0e52d0>)],
      dtype=object), portfolio=array([50, 25, 25], dtype=uint32))


In [5]:
out2 = cp.plan(inputs)
# id, d, sw, gw, price, mr, mc, npv
print(out2[0:5,:])

[[ 2.          2.          1.          0.          1.         21.
  20.          1.        ]
 [ 2.          2.          1.          0.          1.         21.
  20.          1.        ]
 [ 1.          1.          0.          0.          1.          1.81818182
   0.90909091  0.90909091]
 [ 1.          1.          0.          0.          1.          1.81818182
   0.90909091  0.90909091]
 [ 1.          1.          0.          0.          1.          1.81818182
   0.90909091  0.90909091]]
